// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxg8Lmr6C4tmQ3vfg0Gu93meIkkNirmlY',
    appId: '1:205203353546:web:fbac71607cc79a3ce0a933',
    messagingSenderId: '205203353546',
    projectId: 'test6-9f87a',
    authDomain: 'test6-9f87a.firebaseapp.com',
    storageBucket: 'test6-9f87a.appspot.com',
    measurementId: 'G-SKDY2JHK29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkyWxlwia9fFB9VkQBTTNI3fIliDXP9MM',
    appId: '1:205203353546:android:48428b9a28ef4897e0a933',
    messagingSenderId: '205203353546',
    projectId: 'test6-9f87a',
    storageBucket: 'test6-9f87a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyOsXmyu32X37vUi0_qadrm6rG75k09bA',
    appId: '1:205203353546:ios:b38870edabc6a1f3e0a933',
    messagingSenderId: '205203353546',
    projectId: 'test6-9f87a',
    storageBucket: 'test6-9f87a.appspot.com',
    iosClientId: '205203353546-lbf25b3rbaie7d4bo921dknct2m0o64b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );
}
